#!/bin/bash
#
#SBATCH --job-name=sensitivity
#SBATCH --output=res.txt
#SBATCH --ntasks=10
#SBATCH --cpus-per-task=8
#SBATCH --time=10:00
#SBATCH --mem-per-cpu=2048
#SBATCH --array=1-10

export MESA_DIR=~/mesa-r10398
export MESASDK_ROOT=~mesasdk_1_2018
export OMP_NUM_THREADS=8
source $MESASDK_ROOT/bin/mesasdk_init.sh
export MESA_BASE=~/sens/base
export MESA_INLIST=$MESA_BASE/inlist
export MESA_RUN=~/runs

mkdir ~/$MESA_RUN/'SLURM_ARRAY_TASK_ID'
cd ~/$MESA_RUN/'SLURM_ARRAY_TASK_ID'
cat  ~/sens/base/inlist_cluster >./inlist_cluster
rxn=$(sed -n 'SLURM_ARRAY_TASK_ID'p ~/sens/rxn_list.txt)

sed -i "s/reaction_name/$rxn/g"  inlist_cluster

#Run Mesa
$MESA_BASE/star

srun hostname
srun sleep 60